### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by principles31**
# OOP school library: unit tests:
- The goal of this project is to add unit tests to your codebase, specifically to your classes.
- The following were implemented using pair programming in this **PR**.
>  Add unit tests to your classes:
- Book.
- Person.
- Student.
- Teacher.
- Classroom.
- Rental.
- all classes that you created while implementing the Decorator design pattern.

### CODE REVIEW

**Review by DammyShittu — CHANGES_REQUESTED** [review]
Hi team,

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
- [x] You have not written any tests. You need to create a `spec` folder, and within it write the tests for each class in new files. You can visit the links in this lesson on how to write rspec tests in ruby. [https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/rspec_unit_test.md](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/rspec_unit_test.md)

  rspec-1

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principles31** [comment]
@DammyShittu Thanks for the correction, that was an oversight.

**Review by omarsalem7 — APPROVED** [review]
Hi @principles31, @yusufnviiri 😊, 
# STATUS: APPROVED! 🥇 💯 

giphy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project and all tests passed. Keep rocking! 

image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principles31** [comment]
@omarsalem7 Thank you for acknowledging this PR.

**Pull request merged**
